dnfield/flutter_svg

lib/src/render_picture.dart, lib/src/vector_drawable.dart
The old code would translate the image incorrectly when xscale != yscale. Also, I've removed some code duplication.
=> fixed centering of image in scaleCanvasToViewBox()

test/render_svg_test.dart
Fixed the broken Windows path issue in the unit tests. You have to use `Platform.script.toFilePath()` instead of `Platform.script.path` because the latter is the path part of a Uri, but we want an actual file system path.
Now only the PNG comparison and the SvgPicture.network test still fail.
=> fixed path handling on Windows

lib/src/svg/colors.dart, test/colors_svg_test.dart
Tried following the spec more closely.
=> color percentages can be floats and there can be whitespace everywhere

example/main.dart, lib/src/avd/xml_parsers.dart, lib/src/picture_provider.dart
I have two PRs in the queue for this repo and wanted to first bring it up-to-date according to the instructions in the `CONTRIBUTING.md` file.
The deprecated warning was:
```
Analyzing flutter_svg...                                         
info • 'OK' is deprecated and shouldn't be used • lib/src/picture_provider.dart:484:43
1 issue found. (ran in 1.3s)
```
So I switched it to `HttpStatus.ok` because I found that change here:
https://dart-review.googlesource.com/c/sdk/+/61300/2/pkg/analysis_server/tool/instrumentation/server.dart
=> Run "flutter format" and "analyze" and clean up deprecated warning

analysis_options.yaml, lib/src/svg/parser_state.dart
Remove a deprecated one and comment out one that is triggering on new
language features.
=> Fix CI by changing linter options

lib/src/picture_provider.dart, test/widget_svg_test.dart
This way the ExactAssetPicture can use the DefaultAssetBundle derived
from context through the LocalPictureConfiguration instead of always defaulting
to the rootBundle. This is helpful for tests and for local widget
context assets. All other provides just ignore the configuration.
This analogous to the implementation of Image.asset in Flutter.
Fix #117
=> Pass the PictureConfiguration to obtainKey

README.md
Thanks for the package! :) I believe the example requires the comma for it to be runnable code.
On another note, the flutter logo image is broken at https://pub.dartlang.org/packages/flutter_svg. I'm using Chrome but I suspect it has something to with the img `src` is referring to Github which doesn't seem to work for pub?
=> Add missing comma in code example in README.md

.travis.yml, lib/src/vector_drawable.dart
* "Package 'fonts-droid' has no installation candidate"
* `@virtual` is deprecated
=> Fix travis build failed

README.md
I added Adobe illustrator export configuration to guide graphic designers for the right supported format, for example, some SVG images have CSS which is not fully supported but by this guideline most of the issues will be avoided 
related issue https://github.com/dnfield/flutter_svg/issues/207
=> Added Adobe illustrator export configuration

lib/src/svg/colors.dart, test/colors_svg_test.dart
Thanks for an excellent library!
I am using [FramerX](https://www.framer.com/) to create SVGs. Sometimes it uses `fill="transparent"`and `fill="hsl(0,0%,0%)"` etc. I have been manually converting this, though thought it would be nice to just get it out of the box as there are probably other scenarios where this is an issue as well.
The HSL(A) conversion logic is taken from: https://github.com/MichaelFenwick/Color
So big shoutout to @MichaelFenwick for also creating an excellent package ❤️
=> add support for hsl, hsla and transparent fill value

example/assets/simple/image.svg, lib/src/svg/parsers.dart
Adobe Illustrator splits base64 encoded raster images into multiple lines.
This fix strips all whitespace from base64 encoded images instead of only spaces.
Chromium ignores newlines and renders (parses) these images correctly.
=> Strip all whitespace instead of only spaces from base64 encoded images.

CHANGELOG.md, lib/src/picture_stream.dart, pubspec.yaml
Converting these to DiagnosticableMixin, in preparation for eventually deprecating `Diagnosticable`.
=> Diagnosticable => DiagnosticableMixin

lib/src/svg/parsers.dart, test/svg_parsers_test.dart
Given an SVG file with newlines or tabs in a `transform` attribute, `flutter_svg` will throw an exception.
For example, this SVG snippet:
```svg
<g transform="translate(1,1)
scale(10)"></g>
```
Will cause this exception:
```
Bad state: Unsupported transform: 
scale
```
This PR addresses the issue by trimming extra whitespace from around the command, before trying to identify it.
=> Allow additional whitespace between transform commands.

lib/src/svg/parser_state.dart, test/widget_svg_test.dart
Fixes lack of error reporting in #321
=> throw if nested SVG encountered

test/widget_svg_test.dart
With an upcoming change to widget tester, this will cause failures. See: https://github.com/flutter/flutter/pull/57894
=> await runZoned Futures in the tests

lib/src/picture_stream.dart
Now that `Diagnosticable` in Flutter's stable release is a mixin, use that instead, since `DiagnosticableMixin` will be going away. The two mixin classes are identical, so there should be no change in functionality.
=> Switch to Diagnosticable from DiagnosticableMixin

lib/src/svg/parsers.dart, test/svg_parsers_test.dart
Regular Expression was including commas in the matching group. Added a small check to exclude any commas from matches and added tests to validate.
=> Allow multiple transforms in an attribute 

lib/avd.dart, lib/parser.dart, lib/src/svg/parser_state.dart, lib/src/svg/parsers.dart, lib/src/utilities/_http_io.dart, lib/src/utilities/_http_web.dart, tool/gen_golden.dart
As of Dart 2.1, Future and Stream are exported by dart:core
=> Remove unused dart:async imports

lib/src/render_picture.dart
Prepare for introduction of dry layout in https://github.com/flutter/flutter/pull/70656.
This needs to roll into google before https://github.com/flutter/flutter/pull/70656 can be rolled in.
Please wait with submitting this until https://github.com/flutter/flutter/pull/70656 is approved.
=> Prepare for dry layout feature

lib/src/picture_provider.dart
When https://github.com/dart-lang/language/issues/1274 (Infer
non-nullability from local boolean variables) is implemented, flow
analysis will detect that code like this is unreachable:
bool hasArguments = false;
...
if (hasArguments) {
// Not reachable
}
To prepare for this improvement, we need to add an "ignore" comment to
ignore the dead_code warning that will be generated.
=> Ignore dead code warning in preparation for flow analysis improvement.

lib/src/picture_provider.dart
An upcoming feature to the Dart analyzer [0] will report Future.catchError [1]
`onError` handlers which return values of invalid type. Currently this is not
reported because the `onError` handler function type cannot be accurately
expressed. An `onError` handler for `Future<T>.catchError` must be either
`FutureOr<T> Function(dynamic)` or `FutureOr<T> Function(dynamic, StackTrace)`.
In either case, the return type of the function is `FutureOr<T>`.
This CL corrects `onError` handler(s) to return a value of a valid type.
[0]: https://github.com/dart-lang/sdk/issues/35825
[1]: https://api.dart.dev/dev/2.12.0-149.0.dev/dart-async/Future/catchError.html
=> Return valid type from Future.catchError.

CHANGELOG.md, README.md, lib/parser.dart, lib/src/svg/parser_state.dart, pubspec.yaml, test/svg_parsers_test.dart
Adds a dry run mode which will always throw an error aborting the rendering process.
The dry run can be used to check if an SVG is supported by the library.
Closes #473
=> Add warningsAsErrors option for parsing SVGs

lib/src/picture_provider.dart
A similar, but oddly reversed, fix to https://github.com/dnfield/flutter_svg/commit/272f9929f009e0b4e1413095ab4d2e3f3233b8d8.
The issue here is that a `Future<void>`'s catchError onError handler should return `void`. I think this fix is a no-op, because the `Future<PictureStream>` was immediately dropped on the floor. I the important bit in there (`onError(exception, stack);`) remains.
The dart analyzer will start reporting code like this when https://github.com/dart-lang/sdk/issues/35825 is closed.
=> Remove return stmts from Future<void>.catchError

README.md
Alternative for https://github.com/dnfield/flutter_svg/pull/494
Fixes https://github.com/dnfield/flutter_svg/issues/493
@amorenew
I've tried a couple seemingly simple SVGs on this tool though and it produces ... questionable output. I can see some that it does pretty correctly, but other seemingly simple ones that just seem dead wrong to me.
=> Add alternative implementations

lib/src/utilities/xml.dart
Existing implementation uses replaceFirst API which will create a new String. This change replaces it with `localName` API of XmlEventAttribute which internally uses substring.
The end result is overall faster parsing.
=> Refactor attribute localName check

CHANGELOG.md, lib/svg.dart, pubspec.yaml
#500 introduced a number of bugs when people do not specify width and height. This change now preserves old behavior in cases where it's still needed, while still supporting the new test.
=> Fix sizing issues

lib/src/svg/parser_state.dart, lib/src/svg/xml_parsers.dart, lib/src/utilities/numbers.dart, lib/src/utilities/xml.dart, test/xml_svg_test.dart
The previous code used to iterate through a list of XmlEventAttributes for every call to getAttribute. The newer code constructs a Map, and looks up the attribute name directly.
This seems to show a 30% overall reduction to svg parsing costs.
=> Improve performance of SVG parsing

lib/src/svg/parser_state.dart, test/svg_parsers_test.dart
Handle the `xml:space` attribute for `text` and `tspan` elements.
If set to `preserve`, only tabs and newlines will be removed.
=> Add support for xml:space

README.md, lib/src/utilities/xml.dart, lib/src/vector_drawable.dart
I think programmers should be aware that this parameter is not used
=> Unused parameter `bounds` of method draw()

lib/avd.dart, lib/parser.dart, lib/src/picture_provider.dart, lib/src/svg/default_theme.dart, lib/src/svg/parser_state.dart, lib/src/svg/theme.dart, lib/src/svg/xml_parsers.dart, lib/src/vector_drawable.dart, lib/svg.dart, pubspec.yaml, test/default_theme_test.dart, test/picture_cache_test.dart, test/picture_provider_test.dart, test/svg_parsers_test.dart, test/theme_test.dart, test/vector_drawable_test.dart, test/widget_svg_test.dart, test/xml_svg_test.dart, tool/gen_golden.dart
Adds support for [`currentColor`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword) to `SvgPicture`.
- Introduced `SvgTheme` used when parsing an SVG picture (includes `currentColor`).
- Introduced `DefaultSvgTheme`, an inherited widget used to provide `SvgTheme` to `SvgPicture`.
- The `SvgPicture` provides the `currentColor` (from the widget's property if given, otherwise fallbacks to the `currentColor` inherited from `DefaultSvgTheme`) to the `SvgParserState`.
- `SvgParserState` now parses the [`color`](https://www.w3.org/TR/SVG11/color.html) attribute of SVG elements and provides the value to descendant elements. If a nested element defines its color as `currentColor`, then it uses the latest (deepest) `color` defined on its ancestor element. If no …
=> Add support for `currentColor` to `SvgPicture`

pubspec.yaml
The Flutter version constraint is out of date. This PR is bumping it to at least 2.4.0.
The commit that landed `LayerHandle` in flutter/flutter  is https://github.com/flutter/flutter/commit/025397ae3f925b316991912977367d3263cc4432.
=> Requires Flutter >=2.4.0 for LayerHandle usage

CHANGELOG.md, example/lib/simple.dart, lib/src/render_picture.dart, lib/src/svg/parser_state.dart, pubspec.yaml, test/render_picture_test.dart
This is basically https://github.com/dnfield/flutter_svg/pull/655 with a test, and also bumping some changelog/pubspec stuff.
=> Make sure setting a render equal picture does not result in paint updates

lib/src/picture_stream.dart, lib/src/svg/parser_state.dart, lib/svg.dart, test/picture_stream_test.dart, test/widget_svg_test.dart
Fixes an issue where a didUpdateWidget can result in disposing the picture too early.
=> Make sure the SvgPicturestate holds on to a handle

lib/src/vector_drawable.dart, test/vector_drawable_test.dart
The canvas is getting restored in some scenarios one time too much, which will lead to an exception and invalid canvas.
The value of `viewBoxOffset` does not have any effect on saving the canvas initially. The `save()`  is controlled by `transform != null` and eventually restored in L954.
=> Remove redundant canvas.restore()

example/android/app/src/main/AndroidManifest.xml, example/android/gradle/wrapper/gradle-wrapper.properties, lib/src/picture_stream.dart, pubspec.yaml
This PR addresses #708.
Most plugins are migrating to Flutter 3.0 and there has been version solving incompatibilities due to flutter_svg using xml ^5.0.0.
- Updated plugins to latest resolvable
- There were no breaking changes according to their changelogs published in pub.dev
- Dart requirement set to 2.17
- Removed deprecated splash screen. ([See here](https://docs.flutter.dev/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens))
- Removed deprecated **new** keyword in comment reference. ([See here](https://dart.dev/tools/diagnostic-messages#deprecated_new_in_comment_reference))
=> Update project to support flutter 3.0

example/pubspec.yaml
Added a missing dependency to the "example" project to resolve a warning from flutter analyze command:
```
flutter_svg> flutter analyze
Analyzing flutter_svg...
warning - The include file 'package:flutter_lints/flutter.yaml' in '\flutter_svg\example\analysis_options.yaml' can't be found when analyzing
'\flutter_svg\example' - example\analysis_options.yaml:10:10 - include_file_not_found
1 issue found. (ran in 1.6s)
```
=> Added the flutter_lints to the development dependency for project 'example'

CHANGELOG.md, lib/avd.dart, lib/src/svg/parser_state.dart, lib/src/svg/theme.dart, lib/src/utilities/_http_io.dart, lib/src/vector_drawable.dart, lib/svg.dart, pubspec.yaml, test/colors_svg_test.dart, test/vector_drawable_test.dart
Default currentColor to black, mirroring Chrome's behavior.
Update callsites to parseColor so that they account for currentColor.
Avoid setting a default currentColor on the root element when parsing.
Avoid painting when Paint.color == null.
=> Update currentColor handling.

lib/src/loaders.dart
=> Avoid anon closure

README.md
I'm not sure why `AssetLoader()` is included in this sample, but I found that `AssetBytesLoader()` returns the `BytesLoader` that `SvgPicture` expects to receive.
=> README: Remove `AssetLoader()` from the precompiled asset example

CHANGELOG.md, lib/src/loaders.dart, lib/svg.dart
Fixes https://github.com/dnfield/flutter_svg/issues/836
Hides ColorMapper and SvgTheme and provides dart:ui backed versions
=> Hide vector_graphics_compiler types

CHANGELOG.md, analysis_options.yaml, lib/src/cache.dart, pubspec.yaml, test/cache_test.dart
The assertion would fire in the case where a synchronous future was added that was already contained in the cache when the cache was at max capacity.
This broadens the assertion a bit and adds a test. Also bumps VG to newest version.
Fixes #863
=> Fix faulty cache assertion, bump vg

lib/src/loaders.dart, test/loaders_test.dart
Fixes https://github.com/dnfield/flutter_svg/issues/865
See also https://github.com/dnfield/flutter_svg/pull/652
I think it's ok for now because `currentColor` is unlikely to change, and font size is no longer pulled from the build context. I do not intend to make font size come back from context again unless someone really really wants it.
=> Make cache respect SvgTheme

.github/workflows/ci.yml, lib/src/loaders.dart, test/loaders_test.dart
=> Consider colorMapper for cache key data

packages/flutter_svg/CHANGELOG.md, packages/flutter_svg/lib/src/default_theme.dart, packages/flutter_svg/lib/src/loaders.dart, packages/flutter_svg/lib/svg.dart, packages/flutter_svg/test/default_theme_test.dart
Closes https://github.com/dnfield/flutter_svg/issues/953
Some notes/questions:
1. In this PR, I basically copied over the `DefaultSvgTheme` from v1.1.6
2. For the tests, I also copied them except for [this one test](https://github.com/dnfield/flutter_svg/blob/3753ff989c1f7c6ef4781d0772b4a3fe0dde9345/test/default_theme_test.dart#L114-L138) about the `fontSize` being based on the `DefaultTextStyle` because of [this comment](https://github.com/dnfield/flutter_svg/blob/d7b5c23a79dcb5425548879bdb79a5e7f5097ce5/packages/flutter_svg/lib/src/loaders.dart#L20-L26)
3. I noticed that the `SvgTheme` in `flutter_svg/lib/src/loaders.dart` seems to duplicate the one from `vector_graphics_compiler`. Shouldn't we use only the one from `vector_graphics_compiler`?
=> Adds DefaultSvgTheme

packages/flutter_svg/lib/svg.dart
I originally didn't format the debugFillProperties because that seems to be what happens in the main flutter library (presumably for better readability), but here it breaks the presubmits. So here is a quick `dart format`.
=> Fixed formatting broken in #999

packages/flutter_svg/lib/src/loaders.dart
Object.operator== takes an `Object`, and no Dart runtime passes a `null` value to an `==` implementation. SvgTheme's implementation should not have an expanded parameter type of `dynamic`.
See https://github.com/flutter/flutter/issues/117838 for the overarching issue for Flutter.
=> Avoid expanding the parameter type of operator==
