dnfield/flutter_svg

lib/main.dart
pubspec.lock
pubspec.yaml

Quick hacks I had to make to build and run,
feel free to close pull request and implement fixes in different way

Fix error on slider value > max, update flutter min version

---

README.md

Link to the example in `README.md` 404's.

Fix broken link to example

---

lib/src/picture_cache.dart
lib/src/picture_provider.dart
lib/src/picture_stream.dart
lib/svg.dart
test/picture_cache_test.dart

Fixes https://github.com/dnfield/flutter_svg/issues/128
Needs tests.
@Skyost what do you think?

initial implementation of precaching images

---

lib/src/svg/colors.dart
test/colors_svg_test.dart

Hi buddies.
First of all, thx for this library, it's really helpful and easy to use!
I had some issues using files with objects with fill property as rgba color, so I made this little fix, hope its help in some away.

handle rgba colors with alpha as double

---

lib/src/picture_provider.dart
lib/src/picture_stream.dart
lib/src/svg/parser_state.dart
lib/src/utilities/errors.dart
lib/svg.dart

This refactor would be for the branch matching master.

Refactor error messages.

---

analysis_options.yaml
lib/avd.dart
lib/src/picture_provider.dart
lib/src/picture_stream.dart
lib/src/render_picture.dart
lib/src/svg/parsers.dart
lib/src/svg/xml_parsers.dart
lib/src/vector_drawable.dart
lib/svg.dart
test/widget_svg_test.dart
test/xml_svg_test.dart

implicit-cast

---

example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
lib/src/svg/parser_state.dart
lib/src/svg/xml_parsers.dart
lib/src/utilities/xml.dart
pubspec.yaml

Fixes https://github.com/dnfield/flutter_svg/issues/320

Upgrade xml dependency

---

pubspec.yaml

I got a conflict in my project because another dependency was using the latest `xml` version (`4.2.0`). Since it's always good to keep everything up to date, I took the liberty to update all dependencies (they required either patch or minor upgrades, so should be safe). I also ran the whole build pipeline (format, analysis & tests) and it seems to be fine.
I would greatly appreciate if a new version could be released with the updated xml dependency :)

Updating dependencies

---

lib/avd.dart
lib/src/avd_parser.dart
lib/src/svg/parser_state.dart
lib/src/vector_drawable.dart
test/svg_parsers_test.dart
test/vector_drawable_test.dart

support id

---

lib/svg.dart
test/widget_svg_test.dart

Fixes https://github.com/dnfield/flutter_svg/issues/384

Expose clipBehavior from FittedBox

---

lib/src/picture_provider.dart
pubspec.yaml

See discussion at https://github.com/flutter/flutter/pull/69060.

Migrate to Directionality.maybeOf

---

lib/src/picture_provider.dart

See discussion at https://github.com/flutter/flutter/pull/68911
Obv, 1.24.0-8.0.pre hasn't been released yet, but will include the appropriate change when it has been.

Switch to using maybeLocaleOf instead of localeOf

---

lib/src/svg/parser_state.dart
lib/src/svg/xml_parsers.dart
lib/src/utilities/errors.dart
test/error_test.dart

Fixes https://github.com/dnfield/flutter_svg/issues/482

put key into errors

---

.cirrus.yml
CHANGELOG.md
lib/src/picture_cache.dart
lib/src/picture_provider.dart
pubspec.yaml
test/picture_cache_test.dart
test/widget_svg_test.dart

Otherwise, users cannot change the default maximum size of the cache from 1000 (!).

expose cache on PictureProvider

---

lib/src/svg/parser_state.dart
lib/src/utilities/numbers.dart
test/xml_svg_test.dart

Fixes https://github.com/dnfield/flutter_svg/issues/727
Fixes https://github.com/dnfield/flutter_svg/issues/743

handle PT values

---

CHANGELOG.md
lib/src/svg/parser_state.dart
pubspec.yaml
test/svg_parsers_test.dart

Fixes https://github.com/dnfield/flutter_svg/issues/749 (@alexv525).
@jonahwilliams fyi

Default image width/height correclty

---

analysis_options.yaml

See https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks for more info.

Use strict analysis modes instead of deprecated 'strong-mode' options

---

CHANGELOG.md
lib/src/utilities/_compute_io.dart
lib/src/utilities/_compute_none.dart
lib/src/utilities/compute.dart

disable isolate parsing in debug mode

---

lib/svg.dart
pubspec.yaml

See https://github.com/dnfield/vector_graphics/pull/180

Reintroduce clip behavior

---

lib/src/cache.dart
test/cache_test.dart

Fixes https://github.com/dnfield/flutter_svg/issues/883

Manage cache count correctly

---

lib/src/loaders.dart

Fixes https://github.com/dnfield/flutter_svg/issues/888

Allow malformed UTF-8

---

packages/flutter_svg/README.md

Fix typo in README.md

---

packages/flutter_svg/CHANGELOG.md
packages/flutter_svg/lib/svg.dart
packages/flutter_svg/pubspec.yaml
packages/flutter_svg/test/widget_svg_test.dart

Fix semver violation for SvgPicture
